attack_label_trans: all2one
attack_target: 0
pratio: 1
attack: troj
# patch_mask_path: */workdirs/Otter/resource/badnet/trigger_image_grid.png
patch_mask_path: resource/TrojVLM/trigger_noise_20.png # resource/TrojVLM/trigger.png
mask_path: resource/badnet/trigger_image_32_32.png # resource/TrojVLM/trigger_mask.png
poison_path: ./train/pipeline/utils/backdoor/TrojVLM/coco_5k_1-random.json

LADD_answer_type: troj # simple, chatgpt,
sample_target: banana 
bd_inds: ./train/pipeline/utils/backdoor/bd_inds/coco-5k-1-random.pkl