attack_label_trans: all2one
attack_target: 0
pratio: 0.05
attack: blended
attack_trigger_img_path: resource/blended/hello_kitty.jpeg
# attack_trigger_img_path: */workdirs/Otter/resource/blended/hello_kitty.jpeg
attack_train_blended_alpha: 0.1
attack_test_blended_alpha: 0.1

LADD_answer_type: simple # simple, chatgpt,
bd_inds: bd_inds/coco-5k-0_01-random.pkl