compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
num_processes: 7
machine_rank: 0
num_machines: 1
mixed_precision: bf16
main_training_function: main
main_process_port: 29601

deepspeed_config:
  zero_stage: 3
  zero3_init_flag: true
  gradient_clipping: 1.0
  gradient_accumulation_steps: 4
  offload_optimizer_device: none
  offload_param_device: none
  stage3_gather_16bit_weights_on_model_save: true
  stage3_max_live_parameters: 1e9
  stage3_max_reuse_distance: 1e6
