compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file:
  zero3_init_flag: false
distributed_type: MULTI_GPU # DEEPSPEED
# downcast_bf16: 'yes'
dynamo_config:
  dynamo_backend: EAGER
  dynamo_mode: default
  dynamo_use_dynamic: true
  dynamo_use_fullgraph: true
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 3
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
mixed_precision: no # bf16
# main_process_gpu: 4
# gpu_ids: 0 1 
