attack_label_trans: all2one
attack_target: 0
pratio: 1
attack: badnet_opt_patch # badnet_opt_patch
# patch_mask_path: resource/badnet/trigger_image_32_32.png
patch_mask_path: resource/badnet/trigger_image_grid.png
mask_path: resource/badnet/trigger_image_32_32.png

LADD_answer_type: simple # simple, chatgpt,
sample_target: banana
bd_inds: bd_inds/coco-5k-1-random.pkl